// AUTO-GENERATED by scripts/generate-barcodes.mjs
// Do not edit by hand.

export type GeneratedProduct = {
  id: string;
  brand: string;
  name: string;
  price: number;
  barcode: string;
  barcodeType: 'ean13';
  barcodeImage: string;
  imageAsset?: string;
};

export const generatedProducts: GeneratedProduct[] = [
  {
    "id": "nike-af1-goretex-vibram",
    "brand": "Nike",
    "name": "Air Force 1 GORE-TEX Vibram",
    "price": 150,
    "barcode": "2990000000019",
    "barcodeType": "ean13",
    "barcodeImage": "assets/barcodes/nike/nike-af1-goretex-vibram-2990000000019.png",
    "imageAsset": "assets/products/Nike/Air Force 1 GORE-TEX Vibram.png"
  },
  {
    "id": "nike-aj1-low-g",
    "brand": "Nike",
    "name": "Air Jordan 1 Low G",
    "price": 155,
    "barcode": "2990000000026",
    "barcodeType": "ean13",
    "barcodeImage": "assets/barcodes/nike/nike-aj1-low-g-2990000000026.png",
    "imageAsset": "assets/products/Nike/Air Jordan 1 Low G.png"
  },
  {
    "id": "nike-solo-swoosh",
    "brand": "Nike",
    "name": "Nike Solo Swoosh",
    "price": 105,
    "barcode": "2990000000033",
    "barcodeType": "ean13",
    "barcodeImage": "assets/barcodes/nike/nike-solo-swoosh-2990000000033.png",
    "imageAsset": "assets/products/Nike/Nike Solo Swoosh.png"
  }
] as const;

export const generatedProductByBarcode: Record<string, GeneratedProduct> = Object.fromEntries(
  generatedProducts.map((p) => [p.barcode, p])
);
